# PIPELINE DEFINITION
# Name: train-model
# Description: Train Random Forest model and save it.
# Inputs:
#    X_train_csv: str
#    model_path: str
#    y_train_csv: str
components:
  comp-train-model:
    executorLabel: exec-train-model
    inputDefinitions:
      parameters:
        X_train_csv:
          parameterType: STRING
        model_path:
          parameterType: STRING
        y_train_csv:
          parameterType: STRING
deploymentSpec:
  executors:
    exec-train-model:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - train_model
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'kfp==2.15.1'\
          \ '--no-deps' 'typing-extensions>=3.7.4,<5; python_version<\"3.9\"' && \"\
          $0\" \"$@\"\n"
        - sh
        - -ec
        - 'program_path=$(mktemp -d)


          printf "%s" "$0" > "$program_path/ephemeral_component.py"

          _KFP_RUNTIME=true python3 -m kfp.dsl.executor_main                         --component_module_path                         "$program_path/ephemeral_component.py"                         "$@"

          '
        - "\nimport kfp\nfrom kfp import dsl\nfrom kfp.dsl import *\nfrom typing import\
          \ *\n\ndef train_model(X_train_csv: str, y_train_csv: str, model_path: str):\n\
          \    \"\"\"\n    Train Random Forest model and save it.\n    \"\"\"\n  \
          \  X_train = pd.read_csv(X_train_csv)\n    y_train = pd.read_csv(y_train_csv)\n\
          \    model = RandomForestRegressor(n_estimators=100, random_state=42)\n\
          \    model.fit(X_train, y_train.values.ravel())\n    joblib.dump(model,\
          \ model_path)\n    print(f\"Model saved to {model_path}\")\n\n"
        image: python:3.11
pipelineInfo:
  name: train-model
root:
  dag:
    tasks:
      train-model:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-train-model
        inputs:
          parameters:
            X_train_csv:
              componentInputParameter: X_train_csv
            model_path:
              componentInputParameter: model_path
            y_train_csv:
              componentInputParameter: y_train_csv
        taskInfo:
          name: train-model
  inputDefinitions:
    parameters:
      X_train_csv:
        parameterType: STRING
      model_path:
        parameterType: STRING
      y_train_csv:
        parameterType: STRING
schemaVersion: 2.1.0
sdkVersion: kfp-2.15.1
